name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 0.4.5)'
        required: true
        type: string

env:
  NODE_VERSION: '20'

jobs:
  # Build and package Foundry module
  foundry-module:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Extract version
        id: version
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            VERSION="${{ github.event.inputs.version }}"
          else
            VERSION="${GITHUB_REF#refs/tags/v}"
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Version: $VERSION"

      - name: Update module version
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          jq --arg version "$VERSION" '.version = $version' packages/foundry-module/module.json > temp.json
          mv temp.json packages/foundry-module/module.json

      - name: Install dependencies
        run: npm ci

      - name: Build Foundry module
        run: npm run build:foundry

      - name: Create module package
        run: |
          cd packages/foundry-module
          mkdir -p ../../dist/foundry-module
          
          # Copy required files for Foundry module
          cp module.json ../../dist/foundry-module/
          cp -r dist ../../dist/foundry-module/
          cp -r styles ../../dist/foundry-module/
          cp -r lang ../../dist/foundry-module/
          
          # Create ZIP file for Foundry distribution
          cd ../../dist
          zip -r foundry-mcp-bridge.zip foundry-module/
          cp foundry-module/module.json .

      - name: Upload Foundry module artifacts
        uses: actions/upload-artifact@v4
        with:
          name: foundry-module
          path: |
            dist/foundry-mcp-bridge.zip
            dist/module.json

  # Build MCP Server
  mcp-server:
    runs-on: ubuntu-latest
    needs: foundry-module

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci

      - name: Build MCP Server
        run: npm run build:server

      - name: Upload MCP Server artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mcp-server
          path: packages/mcp-server/dist/